name: MLOps Training Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  train: 
    runs-on: ubuntu-latest

    env: 
      AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
      AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
      GH_PAT: ${{ secrets.GH_PAT }}  # GitHub Personal Access Token for pushing changes


    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # get full git history and config files

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install dvc[azure] mlflow xgboost scikit-learn matplotlib seaborn pandas joblib

    - name: Configure Azure credentials for DVC
      run: |
        dvc remote modify azureremote account_name $AZURE_STORAGE_ACCOUNT
        dvc remote modify azureremote account_key $AZURE_STORAGE_KEY

    - name: Pull latest data/model from Azure via DVC
      run: |
        dvc remote modify azureremote account_name $AZURE_STORAGE_ACCOUNT
        dvc remote modify azureremote account_key $AZURE_STORAGE_KEY

    - name: Pull latest data/model from Azure via DVC
      run: |
        dvc pull
        
  
    - name: Train model and log to MLFlow
      run: |
        python train_model.py
    - name: Push the new model & artifacts to Azure
      run: |
        dvc repro train_model -f
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add dvc.lock dvc.yaml .gitignore
        git commit -m "Retrained model and updated artifacts via GitHub Actions"
        dvc push
        git push https://cfikeAI:${GH_PAT}@github.com/cfikeAI/grocerycustomer-xgboost-predictor.git HEAD:main

        

